sudo: required
services:
  - docker
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+$/
  - code-coverage
notifications:
before_install:
  - docker build -t partmc-test .
script:
  - docker run -it partmc-test bash -c 'cd /build; make test'
